### ISSUE TITLE
Add Project Portfolio Page

### ISSUE THREAD

**Issue by harin0826** [AY2223S2-CS2103T-F12-2/tp#17]
### To be done by next tutorial (3 Mar 2023)

Create a skeletal version of your Project Portfolio Page (PPP).
Just the headings are enough. You can write to be added soon as placeholders for content.
PDF conversion not required.

## Objectives

- For you to use (e.g. in your resume) as a well-documented data point of your SE experience
- For evaluators to use as a data point for evaluating your project contributions

## PPP Sections to include
**Overview**: A short overview of your product to provide some context to the reader. The opening 1-2 sentences may be reused by all team members. If your product overview extends beyond 1-2 sentences, the remainder should be written by yourself.

**Summary of Contributions** --Suggested items to include:

- **Code contributed**: Give a link to your code on [tP Code Dashboard]

- **Enhancements implemented**: A summary of the enhancements you implemented.

- **Contributions to the UG**: Which sections did you contribute to the UG?

- **Contributions to the DG**: Which sections did you contribute to the DG? Which UML diagrams did you add/updated?

- **Contributions to team-based tasks**

- **Review/mentoring contributions**: Links to PRs reviewed, instances of helping team members in other ways.

- **Contributions beyond the project team**: 
  - Evidence of helping others e.g. responses you posted in our forum, bugs you reported in other team's products
  - Evidence of technical leadership e.g. sharing useful information in the forum

**Comment by anchengyang** [comment]
All PPP added by @NappySprout
