### ISSUE TITLE
[PE-D][Tester E] Weird error message when deleting module when given a blank as input

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-2/tp#176]
Steps to reproduce:
1. View any existing person
2. Type `edit m-/`

Expected:
Error message saying "Input cannot be black" or "Module does not exist"

Actual:
Error message saying "This person already exist in the address book"

`edit m+/` results in the same issue

![image.png](https://raw.githubusercontent.com/wongyx/ped/main/files/77f9a24f-b076-41af-83ee-078f4cc181a9.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: wongyx/ped#2

**Comment by ShawnYip-Au** [comment]
![Screenshot 2023-04-03 at 8 50 27 PM](https://user-images.githubusercontent.com/86219547/229514619-0ad5b497-2bba-4708-bc8a-eeba43d1ed7c.png)

**Comment by harin0826** [comment]
Closed with #201.
