### ISSUE TITLE
[PE-D][Tester E]  Weird error message when adding/deleting skill when given a blank as input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-2/tp#180]
Steps to Reproduce:
1. View any existing person
2. type `edit s+/` or `edit s-/`

Expected:
Error message saying "Input cannot be blank"

Actual:
Error message saying "This person already exist in the address book"

![image.png](https://raw.githubusercontent.com/wongyx/ped/main/files/15b4b1e5-0075-4ce7-bd52-cfce5dfe346e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: wongyx/ped#3

**Comment by harin0826** [comment]
Closed with #201.
