### ISSUE TITLE
[PE-D][Tester A] Email field in a person can be abnormally long and overflow from the UI

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-2/tp#187]
When an abnormally long email is input for a person, the email address overflows from the UI in both the view panel and the list panel. There are also no options to view more etc to see the entire email, hence I believe that this is a feature bug. 

![Screenshot 2023-03-31 at 3.07.05 PM.png](https://raw.githubusercontent.com/benjamin-wee/ped/main/files/0844fa96-efab-4364-b026-e720c749a932.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: benjamin-wee/ped#5

**Comment by ShawnYip-Au** [comment]
![Screenshot 2023-04-03 at 8 57 00 PM](https://user-images.githubusercontent.com/86219547/229516361-9e279263-e97a-4f91-8b7e-a00ab5984bf9.png)

**Comment by harin0826** [comment]
According to the classification, this is not considered a bug as @ShawnYip-Au mentioned. Regular length emails should be fully displayed in the InfoPanel, and even if it is truncated the copy button is able to copy the full email to the clipboard.
