### ISSUE TITLE
[PE-D][Tester C] Wrong error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-2/tp#190]
If you change the email of someone to be the same as someone else, it shows person already exist error message instead of email being same as someone else. The error message does not reflect the error.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: leonpoh/ped#4

**Comment by harin0826** [comment]
Yeap this is not a bug, having the same email is essentially being the same person in our product scope. Will close the issue after updating the User Guide.

**Comment by ShawnYip-Au** [comment]
UG mentioned that email does not accept duplicates.
