### ISSUE TITLE
[PE-D][Tester B] Bug on name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-2/tp#191]
Some name may contains `.` or `/` in between and also the display result is not shown correctly to the error raised. Example of an Western name and a Malay name respectively
![image.png](https://raw.githubusercontent.com/huanghao1998/ped/main/files/b5d112cd-16cc-48c9-8b13-b91dad887202.png)

![image.png](https://raw.githubusercontent.com/huanghao1998/ped/main/files/7c8fbf21-1a5e-42c0-8490-4863c8b51460.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: huanghao1998/ped#5

**Comment by ShawnYip-Au** [comment]
![Screenshot 2023-04-03 at 9 05 51 PM](https://user-images.githubusercontent.com/86219547/229518490-24d98c0a-da8f-4f39-9b21-e2228ea8c57c.png)

**Comment by harin0826** [comment]
Our feature is able to tolerate majority of possible user inputs, and the users are also given plenty of room to work around implemented conditions. Deemed not a bug, hence closed.
