### ISSUE TITLE
[PE-D][Tester A] Error message is different for invalid negative INDEX inputs for View Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-2/tp#193]
Below shows a screenshot of the error message displayed if the INDEX provided for the view command is negative:

![Screenshot 2023-03-31 at 3.37.05 PM.png](https://raw.githubusercontent.com/benjamin-wee/ped/main/files/d0301cf5-326a-44cd-b346-aec7f8a57852.png)

However, there is a discrepancy in the error message when we use another large negative integer as index, as show below:

![Screenshot 2023-03-31 at 3.38.16 PM.png](https://raw.githubusercontent.com/benjamin-wee/ped/main/files/b963a6d3-f15c-46fd-944b-1965c2d7a80f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: benjamin-wee/ped#6

**Comment by ShawnYip-Au** [comment]
![Screenshot 2023-04-03 at 9 04 26 PM](https://user-images.githubusercontent.com/86219547/229518780-887a2988-eb7b-499a-8cad-df9a4ac497c2.png)

**Comment by harin0826** [comment]
A feature flaw for not checking extreme user input. Not a bug since values outside max range for java integers are "not integers", behavior is unaffected (correctly stops user from viewing a certain person, unless there are `MAX_INT` number of people...), will not be considered for v1.4.
