### ISSUE TITLE
[PE-D][Tester D] Duplicate GitHub and Linkedin Addresses

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-2/tp#195]
# Duplicate GitHub and Linkedin Addresses

![Screenshot 2023-03-31 at 3.37.35 PM.png](https://raw.githubusercontent.com/tituswe/ped/main/files/053e9d44-cd06-42c4-afc0-a09fc122533b.png)

![Screenshot 2023-03-31 at 3.37.42 PM.png](https://raw.githubusercontent.com/tituswe/ped/main/files/99f7a63e-b467-4a66-83e6-f759fb34f67f.png)

### Problem

I am able to create two people with the same GitHub and Linkedin addresses. 

You may consider storing the GitHub and LinkedIn addresses in your `ModelManager` for checking, to ensure that you don't have repeated instances.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: tituswe/ped#6

**Comment by anchengyang** [comment]
can just include in UG for now to say that it allows duplicates

**Comment by linustws** [comment]
added in dg appendix planned enhancements
