### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by harin0826** [AY2223S2-CS2103T-F12-2/tp#20]
## Things to include

1. **Target user profile, value proposition, and user stories**: Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.
2. **Use cases**: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
3. **Non-functional requirements**: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
4. **Glossary**: Define terms that are worth recording.

**Comment by harin0826** [comment]
Just updated the Target user profile, value proposition and user stories (under #27) for DG.
@anchengyang Could you update the remaining sections for the developer guide?

**Comment by anchengyang** [comment]
Just updated the use cases and added 1 more NFR as well @harin0826
Maybe we can leave this issue open because along the way we will need to keep updating the developer guide. Alternatively, we could close this once someone has approved and merged my commits, followed by reopening a new one in the future when changes need to be made. What do you think?

**Comment by harin0826** [comment]
Hi, just looked through the merged commit and it looks good!

I agree with leaving the issue open as you said, we will need to keep updating it. However, it seems that the automatic grading system that tracks our tP progress seems to require us to close the issue first, so why not we close this one first since it has met the requirements for our v1.1 and open a new issue for v1.2 and future iterations?

**Comment by anchengyang** [comment]
Oh alright shall close this issue then!
